package view;

import controller.GerenciadorInterfaceGrafica;
import domain.Cliente;
import domain.ItemVenda;
import domain.Jogo;
import domain.Venda;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author strik
 */
public class DlgCadastrarAdicionarJogo extends javax.swing.JDialog {

    private Cliente clienteSelecionado;
    private List<Jogo> jogosDisponiveis = new ArrayList<>();
    private List<Jogo> jogosVenda = new ArrayList<>();
    private List<Integer> quantidadesVenda = new ArrayList<>();
    private List<Float> subtotaisItens = new ArrayList<>();
    private float valorTotal;
    private final NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

    /**
     * Creates new form DlgPesqJogos
     */
    public DlgCadastrarAdicionarJogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarDesign(parent);
        bntAdicionar.addActionListener(evt -> adicionarItemNaTabela());
        jButton6.addActionListener(evt -> salvarJogo());
        jList1.addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                atualizarPrecoSelecionado();
            }
        });
        jSpinner1.addChangeListener(evt -> atualizarPrecoSelecionado());
        jCheckBox1.setSelected(true);
        carregarJogosDisponiveis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntClassificacao = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bntAdicionar = new javax.swing.JButton();
        BntExcluir = new javax.swing.JButton();
        bntaCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        bntPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bntFinalizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFildPreço = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Jogo", "Quantidade", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bntAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/add (2).png"))); // NOI18N
        bntAdicionar.setText("Adicionar");

        BntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/cross-circle (2).png"))); // NOI18N
        BntExcluir.setText("Excluir");
        BntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntExcluirActionPerformed(evt);
            }
        });

        bntaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/exit (1).png"))); // NOI18N
        bntaCancelar.setText("Cancelar");
        bntaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntaCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente ");

        bntPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/user.png"))); // NOI18N
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogos Disponiveis "));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Resident evil Requim  - R$ 299,99 - Estoque: 20", "Call of Duty - R$ 399,99 - Estoque: 40", "Marvel's Spider-Man 2 - R$199,99 - Estoque : 63", "Mortal Kombat 11 - R$59,99 - Estoque: 103", "Stardew Valey - R$ 19,99 - Estoque: 142" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("R$ 0,0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Valor Total");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Preço Unitário");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("R$ 0,0");

        bntFinalizar.setText("Finalizar");
        bntFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntaCancelar)
                                .addGap(6, 6, 6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAdicionar)
                    .addComponent(BntExcluir)
                    .addComponent(bntFinalizar)
                    .addComponent(bntaCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Adicionar jogo", jPanel1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nome do jogo");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Preço ");

        try {
            txtFildPreço.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Quantidade");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Plataforma");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xbox 360", "PlayStation 4 ", "Xbox Series X", "Xbox Series S", "PlayStation 5 ", "PlayStation 2", "PlayStation 2", "Xbox One " }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Gênero");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Suspense", "Aventura", "RPG", "Estratégia", "Esportes", "Samdox", "Plataforma", " " }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Status");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "12", "16", "18" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Classificação ");

        bntClassificacao.add(jCheckBox1);
        jCheckBox1.setText("Disponível");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        bntClassificacao.add(jCheckBox2);
        jCheckBox2.setText("Indisponível");

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/check.png"))); // NOI18N
        jButton6.setText("Salvar");

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/exit (1).png"))); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(bntCancelar))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFildPreço)
                    .addComponent(jSpinner2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2))
                    .addComponent(jTextField3))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFildPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton1)
                    .addComponent(bntCancelar))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Jogo", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
        DlgPesquisarCliente tela = new DlgPesquisarCliente(obterJanelaPai(), true);
        tela.setLocationRelativeTo(this);
        tela.setVisible(true);

        Cliente cliente = tela.getClienteSelecionado();
        if (cliente != null) {
            clienteSelecionado = cliente;
            jTextField2.setText(cliente.toString());
        }
    }//GEN-LAST:event_bntPesquisarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void BntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntExcluirActionPerformed
        excluirItemSelecionado();
    }//GEN-LAST:event_BntExcluirActionPerformed

    private void bntaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntaCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntaCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limparCamposJogo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntFinalizarActionPerformed
        if (!validarFinalizacao()) {
            return;
        }

        DlgPagamento tela = new DlgPagamento(obterJanelaPai(), true, valorTotal, clienteSelecionado);
        tela.setLocationRelativeTo(this);
        tela.setVisible(true);

        if (tela.isPagamentoConfirmado()) {
            salvarVenda();
        }
    }//GEN-LAST:event_bntFinalizarActionPerformed

    private java.awt.Frame obterJanelaPai() {
        return getOwner() instanceof java.awt.Frame ? (java.awt.Frame) getOwner() : null;
    }

    private Jogo getJogoSelecionado() {
        int indice = jList1.getSelectedIndex();
        if (indice < 0 || indice >= jogosDisponiveis.size()) {
            return null;
        }
        return jogosDisponiveis.get(indice);
    }

    private void atualizarPrecoSelecionado() {
        Jogo jogo = getJogoSelecionado();
        if (jogo == null) {
            jLabel3.setText(formatarMoeda(0));
            return;
        }
        jLabel3.setText(formatarMoeda(jogo.getPreco()));
    }

    private void adicionarItemNaTabela() {
        if (clienteSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Pesquise e selecione um cliente antes de adicionar o jogo.", "Adicionar jogo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Jogo jogo = getJogoSelecionado();
        if (jogo == null) {
            JOptionPane.showMessageDialog(this, "Selecione um jogo disponível.", "Adicionar jogo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int quantidade = (Integer) jSpinner1.getValue();
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "Informe uma quantidade maior que zero.", "Adicionar jogo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        float subtotal = jogo.getPreco() * quantidade;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.addRow(new Object[]{
            clienteSelecionado.getNome(),
            jogo.getNome(),
            quantidade,
            formatarMoeda(jogo.getPreco()),
            formatarMoeda(subtotal)
        });
        jogosVenda.add(jogo);
        quantidadesVenda.add(quantidade);
        subtotaisItens.add(subtotal);
        valorTotal += subtotal;
        atualizarValorTotal();
    }

    private void excluirItemSelecionado() {
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um item da tabela para excluir.", "Adicionar jogo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int linhaModelo = jTable1.convertRowIndexToModel(linhaSelecionada);
        jogosVenda.remove(linhaModelo);
        quantidadesVenda.remove(linhaModelo);
        float subtotal = subtotaisItens.remove(linhaModelo);
        modelo.removeRow(linhaModelo);
        valorTotal = Math.max(0, valorTotal - subtotal);
        atualizarValorTotal();
    }

    private void salvarVenda() {
        Venda venda = new Venda(new Date(), valorTotal, clienteSelecionado);

        for (int i = 0; i < jogosVenda.size(); i++) {
            Jogo jogo = jogosVenda.get(i);
            int quantidade = quantidadesVenda.get(i);
            ItemVenda item = new ItemVenda(quantidade, jogo.getPreco(), venda, jogo);
            venda.getItensVenda().add(item);
        }

        try {
            GerenciadorInterfaceGrafica.getMyInstance().getGerenciadorDominio().inserir(venda);
            JOptionPane.showMessageDialog(this, "Venda registrada com sucesso.");
            limparVendaAtual();
        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(this, "Pagamento confirmado, mas ocorreu erro ao registrar a venda: "
                    + ex.getMessage(), "Finalizar venda", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparVendaAtual() {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        jogosVenda.clear();
        quantidadesVenda.clear();
        subtotaisItens.clear();
        valorTotal = 0;
        atualizarValorTotal();
    }

    private void atualizarValorTotal() {
        jLabel9.setText(formatarMoeda(valorTotal));
    }

    private boolean validarFinalizacao() {
        if (clienteSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente antes de finalizar.", "Finalizar venda", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (((DefaultTableModel) jTable1.getModel()).getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Adicione pelo menos um jogo na tabela.", "Finalizar venda", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    private String formatarMoeda(float valor) {
        return formatoMoeda.format(valor);
    }

    private void ajustarDesign(java.awt.Frame parent) {
        setTitle("Jogos");
        setLocationRelativeTo(parent);
        setResizable(false);
        jTabbedPane1.setTitleAt(0, "Adicionar jogo");
        jTabbedPane1.setTitleAt(1, "Cadastrar jogo");
        jTable1.setModel(new DefaultTableModel(new Object[]{"Cliente", "Jogo", "Qtd.", "Unit.", "Subtotal"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTextField2.setEditable(false);
        jTextField2.setToolTipText("Pesquise e selecione um cliente");
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        txtFildPreço.setFormatterFactory(null);
        txtFildPreço.setText("");
        txtFildPreço.setToolTipText("Exemplo: 18,00");
        bntPesquisar.setToolTipText("Pesquisar cliente");
        bntaCancelar.setText("Cancelar");
        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogos disponíveis"));
        jLabel6.setText("Preço");
        jLabel8.setText("Preço unitário");
        jLabel11.setText("Gênero");
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ação", "Suspense", "Aventura", "RPG"}));
        jLabel12.setText("Situação");
        jLabel13.setText("Classificação");
        jCheckBox1.setText("Disponível");
        jCheckBox2.setText("Indisponível");
        //jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        getRootPane().setDefaultButton(jButton6);
        atualizarPrecoSelecionado();
        atualizarValorTotal();
    }

    private void salvarJogo() {
        String nome = jTextField3.getText().trim();
        String plataforma = String.valueOf(jComboBox1.getSelectedItem());
        String genero = String.valueOf(jComboBox2.getSelectedItem());
        String classificacao = String.valueOf(jComboBox3.getSelectedItem());
        int quantidade = (Integer) jSpinner2.getValue();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do jogo.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            jTextField3.requestFocus();
            return;
        }

        if (plataforma == null || plataforma.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione a plataforma do jogo.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            jComboBox1.requestFocus();
            return;
        }

        if (genero == null || genero.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione o genero do jogo.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            jComboBox2.requestFocus();
            return;
        }

        if (classificacao == null || classificacao.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione a classificacao do jogo.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            jComboBox3.requestFocus();
            return;
        }

        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "Informe uma quantidade maior que zero.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            jSpinner2.requestFocus();
            return;
        }

        if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione a situacao do jogo.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        float preco;
        try {
            preco = lerPreco();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Informe um preço válido para o jogo.", "Cadastro de Jogo", JOptionPane.WARNING_MESSAGE);
            txtFildPreço.requestFocus();
            return;
        }

        Jogo jogo = new Jogo(nome, genero, preco, classificacao);

        try {
            GerenciadorInterfaceGrafica.getMyInstance().getGerenciadorDominio().inserir(jogo);
            JOptionPane.showMessageDialog(this, "Jogo cadastrado com sucesso.");
            limparCamposJogo();
            carregarJogosDisponiveis();
        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar jogo: " + ex.getMessage(), "Cadastro de Jogo", JOptionPane.ERROR_MESSAGE);
        }
    }

    private float lerPreco() {
        String textoPreco = txtFildPreço.getText().trim().replace(" ", "");
        if (textoPreco.isEmpty() || textoPreco.equals(",")) {
            throw new NumberFormatException("Preco vazio");
        }
        textoPreco = textoPreco.replace("R$", "");
        if (textoPreco.contains(",")) {
            textoPreco = textoPreco.replace(".", "").replace(",", ".");
        }
        float preco = Float.parseFloat(textoPreco);
        if (preco <= 0) {
            throw new NumberFormatException("Preco menor ou igual a zero");
        }
        return preco;
    }

    private void limparCamposJogo() {
        jTextField3.setText("");
        txtFildPreço.setValue(null);
        jSpinner2.setValue(1);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jCheckBox1.setSelected(true);
        jTextField3.requestFocus();
    }

    private void carregarJogosDisponiveis() {
        try {
            List<Jogo> jogos = GerenciadorInterfaceGrafica.getMyInstance().getGerenciadorDominio().listar(Jogo.class);
            jogosDisponiveis = jogos;
            DefaultListModel<String> modelo = new DefaultListModel<>();
            for (Jogo jogo : jogos) {
                modelo.addElement(jogo.toString());
            }
            jList1.setModel(modelo);
            if (!jogosDisponiveis.isEmpty()) {
                jList1.setSelectedIndex(0);
            } else {
                atualizarPrecoSelecionado();
            }
        } catch (HibernateException ex) {
            jogosDisponiveis = new ArrayList<>();
            JOptionPane.showMessageDialog(this, "Erro ao carregar jogos: " + ex.getMessage(), "Cadastro de Jogo", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCadastrarAdicionarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCadastrarAdicionarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCadastrarAdicionarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCadastrarAdicionarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCadastrarAdicionarJogo dialog = new DlgCadastrarAdicionarJogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntExcluir;
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntCancelar;
    private javax.swing.ButtonGroup bntClassificacao;
    private javax.swing.JButton bntFinalizar;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JButton bntaCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JFormattedTextField txtFildPreço;
    // End of variables declaration//GEN-END:variables
}
