package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author strik
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPerfil = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        CriarConta = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuConfig = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuPerfil.setMnemonic('o');
        mnuPerfil.setText("Conta");

        mnuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/user.png"))); // NOI18N
        mnuLogin.setText("Login");
        mnuPerfil.add(mnuLogin);

        CriarConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CriarConta.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\user-add.png")); // NOI18N
        CriarConta.setMnemonic('n');
        CriarConta.setText("Criar Conta");
        CriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarContaActionPerformed(evt);
            }
        });
        mnuPerfil.add(CriarConta);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/portrait.png"))); // NOI18N
        jMenuItem10.setMnemonic('P');
        jMenuItem10.setText("Perfil");
        mnuPerfil.add(jMenuItem10);

        mnuConfig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/settings (2).png"))); // NOI18N
        mnuConfig.setMnemonic('g');
        mnuConfig.setText("Configurações");
        mnuPerfil.add(mnuConfig);
        mnuPerfil.add(jSeparator2);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/exit (1).png"))); // NOI18N
        mnuSair.setMnemonic('S');
        mnuSair.setText("Sair");
        mnuPerfil.add(mnuSair);

        jMenuBar1.add(mnuPerfil);

        jMenu2.setText("Biblioteca ");

        jMenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\controle-de-video-game.png")); // NOI18N
        jMenu8.setMnemonic('M');
        jMenu8.setText("Meu jogos");

        jMenu9.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\search (1).png")); // NOI18N
        jMenu9.setText("Filtrar por");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Número de jogadores");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Idioma");
        jMenu9.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Gênero");
        jMenu9.add(jCheckBoxMenuItem3);

        jMenuItem1.setText("Pesquisar");
        jMenu9.add(jMenuItem1);

        jMenu8.add(jMenu9);

        jMenu2.add(jMenu8);

        jMenuItem15.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\familia.png")); // NOI18N
        jMenuItem15.setText("Jogos da famila");
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Loja");

        jMenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\loja-de-jogos.png")); // NOI18N
        jMenu5.setText("Ver loja");

        jMenuItem11.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\search.png")); // NOI18N
        jMenuItem11.setText("Buscar jogos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\lista-de-afazeres.png")); // NOI18N
        jMenuItem3.setText("Lista de desejos");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator1);

        jMenuItem12.setIcon(new javax.swing.ImageIcon("C:\\Users\\strik\\Downloads\\sack-dollar.png")); // NOI18N
        jMenuItem12.setText("Promoções");
        jMenu5.add(jMenuItem12);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/shopping-cart (3).png"))); // NOI18N
        jMenuItem5.setText("Carrinho");
        jMenu5.add(jMenuItem5);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Amigos");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/users-alt (2).png"))); // NOI18N
        jMenuItem6.setText("Ver lista de amigos");
        jMenu4.add(jMenuItem6);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/add (2).png"))); // NOI18N
        jMenuItem8.setText("Adicionar amigo");
        jMenu4.add(jMenuItem8);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/gift.png"))); // NOI18N
        jMenuItem4.setText("Presentear amigo");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ajuda");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/info.png"))); // NOI18N
        jMenuItem7.setText("Sobre o sistema");
        jMenu6.add(jMenuItem7);

        jMenuItem9.setText("Suporte");
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void CriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarContaActionPerformed
        //criar um obj do tipo da janela que vai mostrar, this pq a gente ta programando na janela principal, e true para ela ser modal
        DlgCriarConta objCriarConta = new DlgCriarConta(this, true);
        //pra mostrar a tela criar conta
        objCriarConta.setVisible(true);
    }//GEN-LAST:event_CriarContaActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        DlgPesqJogosLoja objBuscarJogos = new DlgPesqJogosLoja(this, true);
        objBuscarJogos.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows7".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CriarConta;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuConfig;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenu mnuPerfil;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
