package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author strik
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        ajustarDesign();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPerfil = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuConfig = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Cliente");

        pnlInicio.setBackground(new java.awt.Color(18, 78, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GameHub");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 245, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><div style='text-align:center;'>Cadastre clientes, venda jogos e acompanhe compras em um so lugar.</div></html>");

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        mnuPerfil.setMnemonic('o');
        mnuPerfil.setText("Cadastro");
        mnuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPerfilActionPerformed(evt);
            }
        });

        mnuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuLogin.setText("Jogo");
        mnuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginActionPerformed(evt);
            }
        });
        mnuPerfil.add(mnuLogin);

        mnuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/user-add.png"))); // NOI18N
        mnuCadCliente.setMnemonic('n');
        mnuCadCliente.setText("Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuPerfil.add(mnuCadCliente);

        mnuConfig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/settings (2).png"))); // NOI18N
        mnuConfig.setMnemonic('g');
        mnuConfig.setText("Configurações");
        mnuPerfil.add(mnuConfig);

        jMenuBar1.add(mnuPerfil);

        jMenu2.setText("Pesquisar");

        jMenu8.setMnemonic('M');
        jMenu8.setText("Meu jogos");

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/menu-burger.png"))); // NOI18N
        jMenu9.setText("Filtrar por");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Número de jogadores");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Idioma");
        jMenu9.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Gênero");
        jMenu9.add(jCheckBoxMenuItem3);

        jMenuItem1.setText("Pesquisar");
        jMenu9.add(jMenuItem1);

        jMenu8.add(jMenu9);

        jMenu2.add(jMenu8);

        jMenuItem15.setText("Cliente");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Loja");

        jMenu5.setText("Ver loja");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/gift.png"))); // NOI18N
        jMenuItem11.setText("Buscar jogos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem3.setText("Lista de desejos");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator1);

        jMenuItem12.setText("Promoções");
        jMenu5.add(jMenuItem12);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/shopping-cart (3).png"))); // NOI18N
        jMenuItem5.setText("Carrinho");
        jMenu5.add(jMenuItem5);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Ajuda");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/info.png"))); // NOI18N
        jMenuItem7.setText("Sobre o sistema");
        jMenu6.add(jMenuItem7);

        jMenuItem9.setText("Suporte");
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        //criar um obj do tipo da janela que vai mostrar, this pq a gente ta programando na janela principal, e true para ela ser modal
        DlgCadastrarCliente objCriarConta = new DlgCadastrarCliente(this, true);
        //pra mostrar a tela criar conta
        objCriarConta.setVisible(true);
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        DlgCadastrarAdicionarJogo objBuscarJogos = new DlgCadastrarAdicionarJogo(this, true);
        objBuscarJogos.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void mnuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginActionPerformed
        // TODO add your handling code here:
        DlgCadastrarAdicionarJogo objBuscarJogos = new DlgCadastrarAdicionarJogo(this, true);
        objBuscarJogos.setVisible(true);
        
    }//GEN-LAST:event_mnuLoginActionPerformed

    private void mnuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPerfilActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        DlgPesquisarCliente objPesquisarCliente = new DlgPesquisarCliente(this, true);
        objPesquisarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void ajustarDesign() {
        setTitle("Sistema GameHub");
        setLocationRelativeTo(null);
        setMinimumSize(new java.awt.Dimension(720, 480));
        mnuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/user-add.png")));
        mnuConfig.setText("Configurações");
        jMenu8.setText("Meus jogos");
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/menu-burger.png")));
        jCheckBoxMenuItem1.setText("Número de jogadores");
        jCheckBoxMenuItem3.setText("Gênero");
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/gift.png")));
        jMenuItem12.setText("Promoções");
        configurarTelaInicial();
        javax.swing.JMenuItem mnuHistoricoCliente = new javax.swing.JMenuItem("Historico de compras");
        mnuHistoricoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24x24/list_alt_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png")));
        mnuHistoricoCliente.addActionListener(evt -> {
            DlgHistoricoCliente tela = new DlgHistoricoCliente(this, true);
            tela.setVisible(true);
        });
        jMenu2.add(mnuHistoricoCliente);
    }

    private void configurarTelaInicial() {
        pnlInicio.setBackground(new java.awt.Color(18, 78, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 40));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GameHub");

        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
        jLabel2.setForeground(new java.awt.Color(220, 245, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><div style='text-align:center;'>Cadastre clientes, venda jogos e acompanhe compras em um so lugar.</div></html>");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows7".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuConfig;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenu mnuPerfil;
    private javax.swing.JPanel pnlInicio;
    // End of variables declaration//GEN-END:variables
}
